[env]
RUST_LOG = "debug"

# [target.wasm32-unknown-unknown]
# runner = 'wasm-bindgen-test-runner'



[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
ar = "x86_64-w64-mingw32-ar"
